### ISSUE TITLE
FIXME link broken on contributing.md

### ISSUE THREAD

**Issue by fcarvalhopacheco** [carpentries-incubator/introduction-to-conda-for-data-scientists#35]
Hi, 

the link [FIXME](https://swcarpentry.github.io/FIXME) available on [CONTRIBUTING.md](https://github.com/carpentries-incubator/introduction-to-conda-for-data-scientists/blob/gh-pages/CONTRIBUTING.md#where-to-contribute) seems to be broken

Cheers
FP

**Comment by davidrpugh** [comment]
Thanks for the heads up. Fixed!
