### ISSUE TITLE
Adding clarification for using conda + pip

### ISSUE THREAD

**Issue by nsultova** [carpentries-incubator/introduction-to-conda-for-data-scientists#42]
In [01-getting-started-with-conda](https://carpentries-incubator.github.io/introduction-to-conda-for-data-scientists/01-getting-started-with-conda/index.html) there is this passage:

> Conda allows for using other package management tools (such as pip) inside Conda environments, where a library or tools is not already packaged for Conda (we’ll show later how to get access to more conda packages via channels).

As using pip sometimes is unavoidable one should be told that issues can arise when conda and pip are used together,  especially when  used back-to-back multiple times. A short note and a[ link to resources](https://www.anaconda.com/blog/using-pip-in-a-conda-environment) might be sufficient.

**Comment by davidrpugh** [comment]
Indeed. This is another area where the existing materials can be improved.  There is definitely a "right" way to use Conda (+pip) that avoids most issues that I have seen users encounter but I need to do a better job of explain exactly what this "right" way looks like. Here is my recipe for using Conda and Pip together.

* Always explicitly install `pip` in every Conda environment.
* Always be sure your desired environment is active before installing anything using `pip`.
* Prefer `python -m pip install` over `pip install`

Finally when creating Conda envs from `environment.yml` files store all pip installed packages in a `requirements.txt` file and then add the following to your `environment.yml file`.

```yaml
  - pip
  - pip:
    - -r file:requirements.txt
```

Conda will then install your `pip` dependencies using `python -m pip install -r requirements.txt` after create the Conda environment and installing all Conda installable dependencies.

**Comment by davidrpugh** [comment]
@nsultova I have been adding more material to the lecture notes about using Pip and Conda together effectively. See the new episode on Packages and Channels as well as PR #68.
