### ISSUE TITLE
Binder not working? 

### ISSUE THREAD

**Issue by samumantha** [carpentries-incubator/introduction-to-conda-for-data-scientists#43]
Hei,

we just tested the binder link in the setup instructions with a few people, and unfortunately it did not work for anyone.
In some cases a popup suggested: "Build Recommended JupyterLab build is suggested: jupyter-offlinenotebook needs to be included in build", after clicking built it failed to build and nothing more happened and there was nothing more to do. 
In other cases there was no popup suggesting anything, but we were not able to click either files on the left nor launch anything.
I unfortunately do not know what could be wrong here, so it would be great if someone could help to fix :) 

(We will probably be test-teaching this lesson in the beginning of january in Finland-Norway cooperation online)

Greetings,
Samantha

**Comment by davidrpugh** [comment]
@samumantha Apologies for the tardy reply to this as I have been on holiday. I am now back and will look into the issue.

**Comment by davidrpugh** [comment]
@samumantha I too am seeing the popup "Build Recommended JupyterLab build is suggested: jupyter-offlinenotebook needs to be included in build".  However pressing build (which seemed to do nothing) or pressing cancel I was able to launch terminals, Python Consoles, and Jupyter Notebooks and use them without issue.

I am looking into the source of the popup: this extension is part of Binder and not installed by me. It may just require a new build of the image for the workshop. I will try this today and see if it solves the issue.

**Comment by davidrpugh** [comment]
@samumantha @naoe-tatara I have bumped the versions used in `environment.yml` in the `binder` branch to trigger a new build of the image. Everything seems to work as expected now. Can you please test?

**Comment by naoe-tatara** [comment]
Thanks @davidrpugh , I could run the binder and conda command there 👍

**Comment by davidrpugh** [comment]
Great!
