### ISSUE TITLE
conda env export --from-history

### ISSUE THREAD

**Issue by samumantha** [carpentries-incubator/introduction-to-conda-for-data-scientists#45]
in 03- sharing environments is a box stating to beware the conda env export command.

How about suggesting to use  'conda env export --from-history'? 
This then includes only packages specifically installed, so some underlying packages may have different versions on different systems/at different points in time. But the resulting yml can be used across different platforms (to my knowledge).

What do you think?

**Comment by annefou** [comment]
I like your suggestion!

**Comment by samumantha** [comment]
working on a PR on this now.

**Comment by davidrpugh** [comment]
I believe this issue has been addressed in PR #52.

**Comment by samumantha** [comment]
a note here: if no versions were given during 'conda install', there will also be no versions in the resulting environment.yml .
