### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by samumantha** [carpentries-incubator/introduction-to-conda-for-data-scientists#47]
Suggestion to restructure installation instructions:

- binder as a 'last way out', so in the bottom of the page? 
- installation walkthrough for all OS (link downloads something, what to click in installer, etc)
- workspace setup not speciifcly reused in lesson? -> unnecessary at this point?
- mention anaconda navigator - anaconda prompt (why both there for some OS, what to use...?)

Happy to discuss and help to restructure (Ubuntu 16/20 and MacOS mojave available) :)

**Comment by davidrpugh** [comment]
@samumantha have all of these been addressed by PR #49 ?

**Comment by samumantha** [comment]
Not the anaconda navigator, but this is maybe not important for installation.
So will close the issue with this.
