### ISSUE TITLE
Suggestion for rewording the conda vs pip section

### ISSUE THREAD

**Issue by aragilar** [carpentries-incubator/introduction-to-conda-for-data-scientists#5]
Currently the conda vs pip section focuses on the environment management side (which to me isn't a very strong argument), rather than the other advantages of conda (e.g. the use of MKL, cross platform support, and the prebuilt binaries). It also focuses on the conda vs pip issue, rather than why use conda (as opposed to other systems, e.g. docker, spack).

Would you accept a PR which rewords it giving the following points (under the title "Why use Conda":

* Anaconda provides commonly used data science libraries and tools built against Intel's numerical libraries (mention tensorflow here, but I'd add numpy and scipy, and I presume R?)
* Conda is cross platform and support for duplicating your install on other peoples systems (add a link about reproducibility?)
* Pip (and I guess the equivalent R tools?) can be used to install additional things that have not been packaged yet

And then a short section on why not to use conda (prebuilt binaries are slower, not integrated with the rest of the system, so speak to admins of clusters/supercomputers in case they have a better suggestion)?

**Comment by aragilar** [comment]
It's probably worth adding a link to https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/ as well.

**Comment by davidrpugh** [comment]
Thanks for you feedback and interest in contributing! I will happily accept a PR to improve the discussion of `conda` vs `pip` section.  

However I would like to have a separate issue and PR around when not to use `conda`.  There has been additional discussion on this point via the carpentries discussion email list which I want to capture in a separate issue. I will open a new issue later today.
