### ISSUE TITLE
separate 'use of conda + pip' 

### ISSUE THREAD

**Issue by samumantha** [carpentries-incubator/introduction-to-conda-for-data-scientists#62]
Hei,

this is a suggestion to gather all pip related information and exercise at the end of lesson 3 except for the pip in environment files.
This could be a whole own section there, with explanation what is pip, why pip useful also when using conda, and how it can be used together and what may happen if pip is not explicitly installed into an environment.

**Comment by samumantha** [comment]
also related to #42

**Comment by davidrpugh** [comment]
Closing this issue as I think I have collected all the `pip` related material into the end of episode 3 (except for the usage of `pip` inside environment files which is now in episode 4).
